### ISSUE TITLE
Solution maybe? to controller still locking out after lock pick

### ISSUE THREAD

**Issue by ReloadlI** [Wildlander-mod/Support#13]
Hey, saw this reddit thread about the controller issue
https://www.reddit.com/r/wildlander/comments/vhnuyz/controller_still_locking_out_after_lock_pick/

FIxed it for me with disabling "Auto Input Switch" and installing "Hanks Gamepad and Controller fixes"
https://www.nexusmods.com/skyrimspecialedition/mods/42492?tab=files&file_id=214056

Thought I should let you know since I don't have a Reddit account. Don't know the side effects, but from the description it seems to be close to "Auto Input Switch" with less features.

**Comment by Mieekaserra** [comment]
Update:
This mod is half obsolete now because you should go and use Parapets' new mod, [Auto Input Switch](https://www.nexusmods.com/skyrimspecialedition/mods/54309)! It does the simultaneous keyboard/controller input my mod does, but better, as it updates the buttons in the UI, and allows you to use the mouse as well!

its right at the top of the mod page :)

**Comment by ReloadlI** [comment]
Yes, I'm aware but unlike "Auto Input Switch" it doesn't lock you out after lockpicking. I guess it's exactly because of the missing mouse functions and for me I just need the bound keys in Wildlander and not a mouse while I'm using a controller.

**Comment by Mieekaserra** [comment]
will be fixed in 1.1.6
